name: deploy to gcp

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps: 
    - name: Checkout
      uses: actions/checkout@v3 